services:
  shell-compiler:
    build: .
    image: shell-compiler
    container_name: compiler-box
    volumes:
      - ./src/:/home/shell-compiler/src # Mount project directory
      #- /tmp/.X11-unix:/tmp/.X11-unix # Used for GUI applications
      #- apt-cache:/var/cache/apt
      #- apt-lib:/var/lib/apt
    stdin_open: true # docker run -i
    tty: true        # docker run -t
#volumes:
#  apt-cache: {} # Empty brackets specify default configuration
#  apt-lib: {}